name: http_test_client
version: 0.0.1
author: jonah williams <jonahwilliams@google.com>
description: A package for testing http clients on flutter or the Dart vm.
homepage: https://github.com/jonahwilliams/http_test_client

dev_dependencies:
  test: ^0.12.32

environment:
  sdk: '>=1.19.0 <2.0.0'
