name: fake_http_client
version: 0.0.2
description: A package for faking Dart HttpClient's responses.
homepage: https://github.com/Pavel-Sulimau/fake_http_client

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
  http: ^0.12.2
