name: fake_http_client
version: 0.0.2
author: Pavel Sulimau <pavel.sulimau@gmail.com>
description: A package for faking Dart HttpClient's responses.
homepage: https://github.com/Pavel-Sulimau/http_test_client

environment:
  sdk: '>=2.9.1 <3.0.0'

dev_dependencies:
  test: 1.15.7
  http: 0.12.2
