name: fake_http_client
version: 0.0.3
description: >-
  A package for faking Dart/Flutter HttpClient's responses.
  It is handy for integration tests. Also it may help a lot during 
  app development with an unstable back-end.
homepage: https://github.com/Pavel-Sulimau/fake_http_client

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
  http: ^0.12.2
